from __future__ import annotations

# Fresh human-written prompts. These are intentionally not generated by the v19 training
# templates and are checked for exact normalized overlap in test_v19_intelligence.py.
V19_HOLDOUT_CASES: tuple[tuple[str, tuple[str, ...]], ...] = (
    # Semantic ratio binding / split semantics (8)
    ("مبلغ 840 را میان دو نفر به نسبت 5 به 2 تقسیم کن", ("600", "240")),
    ("عدد 990 را با نسبت 7 به 4 بین دو بخش پخش کن", ("630", "360")),
    ("360 را میان دو گروه با نسبت 1 به 2 تقسیم کن", ("120", "240")),
    ("بودجه 1250 را به نسبت 3 به 2 تقسیم کن", ("750", "500")),
    ("مقدار 728 را بین دو سهم با نسبت 5 به 3 تقسیم کن", ("455", "273")),
    ("420 را با نسبت 2 به 5 بین دو نفر تقسیم کن", ("120", "300")),
    ("مبلغ 1440 را میان A و B به نسبت 7 به 5 تقسیم کن", ("840", "600")),
    ("جمع 650 را به نسبت 8 به 5 بین دو بخش تقسیم کن", ("400", "250")),

    # Probability must outrank generic percentage (8)
    ("شانس موفقیت هر تلاش 25 درصد است؛ در 5 تلاش دقیقاً 2 موفقیت چقدر احتمال دارد؟", ("26.367",)),
    ("احتمال موفقیت 40 درصد است؛ در 3 بار دقیقاً 1 موفقیت؟", ("43.2",)),
    ("با شانس 60 درصد در هر آزمون، در 4 آزمون دقیقاً 3 موفقیت چه احتمالی دارد؟", ("34.56",)),
    ("احتمال هر برد 20 درصد است؛ در 6 بار دقیقاً 2 برد چقدر است؟", ("24.576",)),
    ("success probability is 50 percent; in 4 trials exactly 2 successes?", ("37.5",)),
    ("chance per trial is 30 percent; in 5 trials exactly 1 success?", ("36.015",)),
    ("per-trial probability is 70 percent; over 3 trials exactly 2 successes?", ("44.1",)),
    ("success chance is 10 percent; in 2 attempts exactly 1 success?", ("18%",)),

    # Execution graph / multistep (10)
    ("800 را 25 درصد کم کن و بعد 50 اضافه کن", ("650",)),
    ("200 را 10 درصد زیاد کن سپس 20 کم کن", ("200",)),
    ("1000 را 15 درصد کم کن و بعد 2 برابر کن", ("1700",)),
    ("500 را 20 درصد زیاد کن و سپس 100 اضافه کن", ("700",)),
    ("300 را 10 درصد کم کن و بعد 30 کم کن", ("240",)),
    ("120 را 25 درصد زیاد کن سپس بر 3 تقسیم کن", ("50",)),
    ("90 را 10 اضافه کن و بعد در 2 ضرب کن", ("200",)),
    ("400 را 50 کم کن سپس بر 7 تقسیم کن", ("50",)),
    ("250 را 20 درصد کم کن و بعد 25 اضافه کن", ("225",)),
    ("640 را 25 درصد کم کن سپس 80 کم کن", ("400",)),

    # Age reasoning, colloquial + English (8)
    ("علی 12 ساله است و خواهرش 4 سال بزرگ‌تر است؛ 3 سال بعد مجموع سنشان چند می‌شود؟", ("34",)),
    ("مریم الان 10 سالشه و برادرش 2 سال بزرگ‌تره؛ 5 سال بعد مجموع سنشان؟", ("32",)),
    ("رضا 14 سال دارد و خواهرش 3 سال کوچک‌تر است؛ 4 سال دیگر جمع سن آن‌ها؟", ("33",)),
    ("Sara is 11 years old; her brother is 5 years older. What is their total age 2 years later?", ("31",)),
    ("Tom is 9 years old and his sister is 2 years younger. What is their combined age 6 years later?", ("28",)),
    ("سن نیما 8 سال است، برادرش 6 سال بزرگ‌تر است؛ 7 سال بعد مجموع سن؟", ("36",)),
    ("Lina is 15 years old; her sister is 4 years younger. Total age 3 years later?", ("32",)),
    ("حسام 13 ساله است و خواهرش 1 سال بزرگ‌تر است؛ 10 سال دیگر مجموع سنشان؟", ("47",)),

    # Code intent -> algorithm -> code (8)
    ("یک تابع پایتون بنویس که فقط اعداد مثبت آرایه را برگرداند", ("filter_positive", "x > 0")),
    ("تابعی بساز که بزرگ‌ترین مقدار یک لیست را پیدا کند", ("max_value", "max(values)")),
    ("یک API خیلی ساده با Flask بساز", ("Flask", "/health")),
    ("تابع Python بنویس که اعداد زوج لیست را جدا کند", ("filter_even", "% 2")),
    ("تابعی بنویس که لیست را مرتب کند", ("sort_values", "sorted(values)")),
    ("یک تابع بساز که مجموع عناصر لیست را حساب کند", ("sum_values", "sum(values)")),
    ("Write a Python function that returns only positive numbers from a list", ("filter_positive", "x > 0")),
    ("Create a tiny Flask API with a health endpoint", ("Flask", "/health")),

    # Work-rate order independence (4)
    ("4 کارگر در 6 ساعت 120 قطعه می‌سازند؛ 8 کارگر در 3 ساعت چند قطعه می‌سازند؟", ("120",)),
    ("در 5 ساعت 3 کارگر 90 کالا تولید می‌کنند؛ 6 کارگر در 10 ساعت چند کالا؟", ("360",)),
    ("2 workers make 80 items in 4 hours; how many items do 5 workers make in 8 hours?", ("400",)),
    ("در 7 ساعت 5 کارگر 140 واحد تولید می‌کنند؛ 10 کارگر در 2 ساعت چند واحد؟", ("80",)),

    # Sequence collision guard + ordinal understanding (4)
    ("دنباله هندسی از 5 با نسبت 2 داریم. جمله 7 چیست؟", ("320",)),
    ("در دنباله هندسی با جمله اول 3 و نسبت 4، جمله پنجم چیست؟", ("768",)),
    ("A geometric sequence starts at 2 with ratio 3. What is term 5?", ("162",)),
    ("دنباله هندسی 7 با نسبت 2؛ جمله چهارم چند است؟", ("56",)),
)
